source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JRPopupView_Example', :exclusive => true do
  pod 'JRPopupView', :path => '../'
end

target 'JRPopupView_Tests', :exclusive => true do
  pod 'JRPopupView', :path => '../'

  pod 'FBSnapshotTestCase'
end
